name: flutter_myinsta
description: Instagram clone application h.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.6.6+5
  flutter_icons: 1.1.0
  cached_network_image: ^2.5.0
  fluttertoast: 7.1.1
  shared_preferences: 0.5.12
  firebase_core: 0.4.4
  firebase_auth: 0.16.0
  firebase_storage: 3.1.6
  cloud_firestore: 0.13.5
  device_info: ^2.0.0
  firebase_messaging: ^4.0.0+3
  flutter_local_notifications: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf